excluded:
- Pods
- SwiftLint/Common/3rdPartyLib
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
function_body_length:
    warning: 300
    error: 500
cyclomatic_complexity:
    warning: 25
    error: 35
reporter: "xcode"