# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'Poke-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poke-test
	pod 'Alamofire', '~> 5.4'
  pod 'AlamofireImage', '~> 4.1'

end
