# Uncomment the next line to define a global platform for your project
platform :ios, '12.0' #12.0

target 'Poke-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poke-test
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'IQKeyboardManagerSwift'

end
